### PR TITLE
Restructure of Query object

### PR DESCRIPTION
**Pull request by roarbra**
Introdusing list function, replacing old map
Adding lambda as argument to map-function for iteration over all items of result. In a asynchronously manner.
Removing table as an argument for both list and map. Instead it should be set in the init.

### CODE REVIEW

**Comment by JamesSample** [comment]
Hi @roarbra, Hope you had a good summer!

I haven't looked at this in detail yet, but from a quick skim it looks good. I've made a few changes to the `get_project_chemistry` function so that it works with your new Query object. I also applied code formatting using [black ](https://github.com/psf/black) just for consistency. Hope this is OK.

My main comment from brief testing is that the new version seems much slower than the old one. For example, running section 4 of the [test notebook](https://github.com/NIVANorge/Aquamonitor-Python/blob/master/examples/query_chem.ipynb) on the JupyterHub (the part using `get_project_chemistry`), the version on `master` typically takes 25 to 30 seconds to get the 1000 Lakes data, whereas the new version on this branch takes around 1.5 minutes. Any idea why this might be?

**Comment by roarbra** [comment]
Regarding the time loss: I fixed the code so that the map function is used correctly. We might consider to do the json_normalize differently. Maybe collect everything first in one big json. I see from the log-files that we can do far better by running that for-loop in parallell, but I'm not that familiar with Python. I've tried to extract some of the timings beneath. Value in parenthesis represents time from "Start create query".

Start create query: ___________10:42:05.6574  (0.0 s)
Response query created: ____10:42:07.4145 (1.7571 s)
First page ready: ____________10:42:08.0075 (2,3501 s)  
First page sent: _____________10:42:09.6245 (3,9671 s) 
Second page requested: ___ 10:42:11.4645 (5,8071 s)
Last page ready: ____________10:42:12.5845 (6,9271 s)
Last page sent: _____________10:43:04.8676 (59,2102 s)

I've installed "black", but can't promise to use it every time.

**Comment by JamesSample** [comment]
Thanks Roar! 

However, even with these changes, this approach still seems slow compared to the version currently on `master` (just tested now with your latest changes and my benchmark query took about 1m 40s, compared to 30s for the version on `master`).

Running these queries in parallel is a very good idea though 👍  This is actually pretty easy to implement for the old version (on `master`) using `joblib`. Something like:

``` python
def page_parser(pages_obj, page_no):
    """Parse a single page from a pages object and return a dataframe."""
    return json_normalize(pages_obj.fetch(page_no))

df_list = Parallel(n_jobs=n_jobs, prefer="threads")(delayed(page_parser)(pages, page) for page in range(pages.pages)) 
```

Based on some rough testing, it seems we can reduce the query time by a factor of ~3. Here's an example running multithreaded to query the 1000 Lakes data:

query_times

I think it will be a bit more complicated to implement parallelisation for the new `Query` object (on this branch), though, since it now returns a generator. I'm sure it's still possible, but before digging deeper it would be good to understand if/why the new version is inherently slower (because a ~3x speed up of the new version will still only be about as fast as the old version running single-threaded).

Cheers!

**Comment by roarbra** [comment]
Hi James,
I think it's great that we can work at this from both sides. The answer for your question about why it became slower is that the map function split's up the result into objects for each value. That would be >30000 objects, and using json_normalize on that isn't very efficient. I did a rewrite of your code and turned it into a more straight forward build-up of the dataframe. Then I got down to ~30 sec.

You're right about the parallelization and my map-function. They doesn't fit nice together. The benefit of the map function would be that in an interactive solution, we would get the first response early. For your jupyter solution, that wouldn't be much of a benefit. So you could as well use the old function.

I do have some input for your testing yesterday. There are totally 35 pages for this query. So using more than 35 threads would be excessive. The other thing is that the fetch function is throwing an exception if the page isn't ready. If you call that function for all the pages at once, I would certainly believe that some get that exception. Do you know how that is handled by the delayed function? I would certainly like to look more into this. Another thing to look at is the size of the page at the server.

Here is the same timings as earlier, with the new approach:

Start create query: ___________11:22:40.6567  (0.0 s)
Response query created: ____11:22:42.3257 (1.669 s)
First page ready: ____________11:22:43.9910 (3,3343 s)  
First page sent: _____________11:22:45.0670 (4,4103 s) <----
Second page requested: ___ 11:22:45.5060 (4,8493 s) <---- **The difference between these two are down from 1,84 s**
Last page ready: ____________11:22:47.9251 (7,2684 s)
Last page sent: _____________11:23:05.5805 (24,9238 s)

**Comment by JamesSample** [comment]
Hi Roar,

Thanks for the explanation and for refactoring the code to work with the new `map` function! I've just tested on my system and performance is now the same as the old version, like you say 🎉  I've re-added one line of my original code (`df.dropna(subset=["value"], inplace=True)`) as the API sometimes returns rows where the `value` is NaN (209 rows in the test example). I'm not sure if this is intended, but they don't have much meaning for analysis and I've previously filtered them out. With this modification,  your refactored version gives exactly the same result as the original 👍 

I see your point regarding the benefits of having a generator for more "interactive" applications. Do you think there's an argument for keeping both versions i.e. keep the old map with the parallel "fetch" for bulk download (e.g. via Jupyter) and have the new version for more interactive work? I'm not sure what the best/clearest way to organise this would be, but I don't see it causing too many issues (except maybe some additional work to maintain?).

You raise some interesting points in your last paragraph. I've now created a new branch called `parallel_fetch` for this and modified my code so that by default the number of threads is equal to the number of pages, which seems like a sensible starting point. 

Regarding the `Page not ready` exception, all I can say for the moment is that I haven't run into this yet in any of my testing so far. I agree this is surprising! I don't have much experience of parallelising network requests with `joblib` (I've mostly used it for parallel machine learning workflows in scikit-learn), but I don't think it does anything unusual/clever regarding exception handling. I've briefly tested this by adding a print statement to the `fetch` function, like this:

```
            if not resp.get("Items") is None:
                return resp.get("Items")
            else:
                print("Page not ready.")
                raise Exception("Page wasn't ready.")
```

and, so far, I have not managed to create any situation where that `else` statement is executed. This includes querying much larger datasets, such as all data from Elveovervåkingsprogrammet since 1990 (more than 260 "pages" on the server). The performance is consistently 3 to 4 times faster than running the query single-threaded and the pages always seem "ready" when `joblib` asks for them. There's obviously some stuff happening here that I don't fully understand yet - I'll dig a little deeper when I get chance.

**Comment by roarbra** [comment]
You're right about the nan in Value. That is an error within the server code. It should be a 0.

I did intend to keep the old function, but rename it to pages().

And also have a list() function that return all the objects in an array. This could be extended by using your parallel-approach.

**Comment by JamesSample** [comment]
Sounds good Roar!

Will you fix the NaN error on the server side? (As a temporary fix I can use `fillna(0)` instead of `dropna` in the query function).

**Comment by roarbra** [comment]
There should be no need for fillna. I've included it at the server side. Would be nice if these cases got into an Issue in AquaMonitor.

**Comment by JamesSample** [comment]
Small update regarding the multiprocessing:

I just did some profiling of my code and noticed that in the version on `master`, `query.map` takes up a significant chunk of the total runtime. For example, if I query all data from Elveovervåkingsprogrammet from 1990 to 2020, I get a server response with 296 pages. Running this query with 296 threads, the whole request takes roughly a minute, and this time is split approximately equally between the call to `pages = query.map(table)` (~30s) and the parallel request using `joblib`.

I think `query.map` is using `waitQuery` to ensure all pages are ready before the `Pages` object is returned? In other words, for the first 30s the code is basically paused waiting for the pages to be generated on the server, and then the download happens rapidly in parallel once everything is ready?

Does that sound right, Roar? It would explain why I'm not seeing `Page not ready` errors despite using so many threads (but also suggests potential for further performance improvements).

**Comment by roarbra** [comment]
Hi James,
You're right about that "Page not ready". The code will not go out and fetch a page that isn't ready. The map-function have this structure:
1 - Wait for query is created - That means that there wasn't any error in the description, and a process have started to query the database.
2 - Check that there is minimum one page within result - It will receive the total number of pages that are ready.
3 - Iterate over all Pages that are ready, and call the function for each item.
4 - Check if there's a new total of pages, or if the query has ended.
5 - If there is a new total of pages, repeat step 3

I included some print statements, and as you can see. It works:

df = am.get_project_chemistry(12433, "01.01.2019", "31.12.2019", am.login())
Fetch page 1 of 11
Fetch page 2 of 11
Fetch page 3 of 11
Fetch page 4 of 11
Fetch page 5 of 11
Fetch page 6 of 11
Fetch page 7 of 11
Fetch page 8 of 11
Fetch page 9 of 11
Fetch page 10 of 11
Fetch page 11 of 11
Check for new pages.
Fetch page 12 of 36
Fetch page 13 of 36
Fetch page 14 of 36
Fetch page 15 of 36
Fetch page 16 of 36
Fetch page 17 of 36
Fetch page 18 of 36
Fetch page 19 of 36
Fetch page 20 of 36
Fetch page 21 of 36
Fetch page 22 of 36
Fetch page 23 of 36
Fetch page 24 of 36
Fetch page 25 of 36
Fetch page 26 of 36
Fetch page 27 of 36
Fetch page 28 of 36
Fetch page 29 of 36
Fetch page 30 of 36
Fetch page 31 of 36
Fetch page 32 of 36
Fetch page 33 of 36
Fetch page 34 of 36
Fetch page 35 of 36
Fetch page 36 of 36
Check for new pages.

The other thing of interest is that I timed it to 16 s. I'm sitting in Ø94.

**Comment by roarbra** [comment]
Hi James,

I've now landed on three different functions within Query-object for getting the result:

- list
- pages
- map

If table is specified in the Query we will get these results:

list - An array with all the objects from the given table.
pages - The Pages-object with a total of Pages in the result. Making it possible to iterate yourself.
map - Taking a function as argument, and iterating over all the objects with that function.

If table isn't specified, the query is taken as a query for stations. It will give these result:

list - An array with all the station-id's
pages - An exception
map - Taking a function as argument, that does something with each station-id.

I've gone through all the examples. Could you do the same with your stuff?

**Review by JamesSample — APPROVED** [review]
This looks great Roar!

(Sorry for the slow reply – I’ve just found time to look at it).

I’ve tested the new methods in my “standard” Jupyter workflow and they work well. The new `list` and `pages` methods in particular will be useful for querying data as dataframes via `aquamonitor-python` and `aquamonitR` (e.g. for JupyterHub) and, as you say, the improved `map` method will be useful for more interactive work.

For the `get_project_chemistry` function I did some basic benchmarking using the 1000 Lakes data as an example (see plot below). The parallel implementation of the pages method is consistently fastest, and also has lower variance (black lines on the bar plots show a 95% confidence interval around the mean query time). I have therefore modified `get_project_chemistry` to run in parallel and added joblib to `requirements.txt`.

query_times

I’ll need to give some thought regarding how to implement both this and your new methods in `aquamonitR`, but that will have to wait until I have more time. I’ll create an issue in that repository for this and will probably ask Dag for some advice.

Happy for you to merge this to `main` when you're ready.

**Comment by roarbra** [comment]
Thank for the cooperation @JamesSample . Would've been nice if every process had been that constructive.

**Pull request merged**
